export const plants = [
  {
    name: "Fikus Elastica",
    price: 10,
    image: "../images/fikus.jpeg",
    rating: 4.1,
    id: 1,
    description:
      "Ficus elastica is a popular houseplant with large glossy leaves in dark green or variegated patterns. Known for its air-purifying qualities, it grows slowly but can reach 2-3 meters in height.",
    type: "Decorative foliage plant",
    difficulty: "Beginner-friendly",
    light: "Bright indirect light (tolerates partial shade)",
    watering: "Moderate",
    petFriendly: false,
  },
  {
    name: "Aglaonema",
    price: 15,
    image: "../images/aglaonema.jpeg",
    rating: 4.2,
    id: 2,
    description:
      "Aglaonema is a stunning tropical plant with striking patterned leaves in silver, red, or green variations. It's highly adaptable and known for its excellent air-purifying abilities. Grows compactly, typically reaching 30-60cm indoors",
    type: "Decorative foliage plant",
    difficulty: "Beginner-friendly",
    light: "Low-light",
    watering: " Moderate ",
    bonus: "Air-purifying plant",
    petFriendly: false,
  },
  {
    name: "Fittonia",
    price: 20,
    image: "../images/fittonia.jpeg",
    rating: 4.3,
    id: 3,
    description:
      "Aglaonema is a stunning tropical plant with striking patterned leaves in silver, red, or green variations. It's highly adaptable and known for its excellent air-purifying abilities. Grows compactly, typically reaching 30-60cm indoors",
    type: "Decorative foliage plant",
    difficulty: "Intermediate",
    light: "Low-light",
    watering: "Regular",
    petFriendly: true,
  },
  {
    name: "Cactus",
    price: 25,
    image: "../images/cactus.jpeg",
    rating: 4.0,
    id: 4,
    description: "",
    type: "Succulent plant",
    difficulty: "Beginner-friendly",
    light: "Bright direct light",
    watering: "Drought-tolerant",
    petFriendly: true,
  },
  {
    name: "Rubber Plant",
    price: 30,
    image: "../images/succulent.jpeg",
    rating: 4.4,
    id: 5,
    description: "",
    type: "Succulent plant",
    difficulty: "Beginner-friendly",
    light: "Bright indirect light",
    watering: "Moderate",
  },
  {
    name: "Money Tree",
    price: 35,
    image: "../images/tolstyanka.jpeg",
    rating: 4.1,
    id: 6,
    type: "Decorative foliage plant",
    difficulty: "Beginner-friendly",
    light: "Bright indirect light",
    watering: "droght-tolerant",
    bonus: "Pet-friendly",
    petFriendly: true,
  },
  {
    name: "Spatifillum",
    price: 40,
    image: "../images/spatifillum.png",
    rating: 3.9,
    id: 7,
    description: "",
    type: "Flowering foliage plant",
    difficulty: " Beginner-friendly ",
    light: "Low-light",
    watering: "Regular",
    bonus: "Air-purifying plant",
    petFriendly: false,
  },
  {
    name: "Sansevieria",
    price: 45,
    image: "../images/sansevieria.jpeg",
    rating: 4.2,
    id: 8,
    description: "",
    type: "Succulent plant",
    difficulty: "Beginner-friendly",
    light: "Low-light",
    watering: "Drought-tolerant",
    bonus: "Air-purifying plant",
    petFriendly: false,
  },
  {
    name: "Zamiokulkas",
    price: 8,
    image: "../images/zamiokulkas.jpeg",
    rating: 4.0,
    id: 9,
    description: "Shiny, waxy leaves on arching stems that thrive on neglect.",
    type: "Succulent plant",
    difficulty: "Beginner-friendly",
    light: "Low-light to bright indirect",
    watering: "Drought-tolerant (every 3-4 weeks)",
    bonus: "Air-purifying",
    petFriendly: false,
  },
  {
    name: "Epipremnum aureum",
    price: 12,
    image: "../images/epipremnum.jpeg",
    rating: 4.0,
    id: 10,
    description:
      "Trailing vine with heart-shaped leaves in green, golden, or marble patterns.",
    type: "Vining plant",
    difficulty: "Beginner-friendly",
    light: "Low-light to bright indirect",
    watering: "Moderate (when soil dries out)",
    bonus: "Fast-growing + removes formaldehyde",
    petFriendly: false,
  },
  {
    name: "Ceropegia woodii",
    price: 16,
    image: "../images/woodii.jpeg",
    rating: 4.0,
    id: 11,
    description:
      "Delicate trailing vine with heart-shaped, silver-patterned leaves and occasional pink flowers.",
    type: "Vining plant (succulent)",
    difficulty: "Beginner-friendly",
    light: "Bright indirect (tolerates medium light)",
    watering: "Drought-tolerant (every 2-3 weeks)",
    bonus: "Fast-growing + rare purple blooms",
    petFriendly: true,
  },
  {
    name: "Calathea orbifolia",
    price: 20,
    image: "../images/calathea.jpeg",
    rating: 4.0,
    id: 12,
    description:
      "Striking foliage with vibrant patterns of pink, white, or silver veins. Leaves fold upward at night like praying hands.",
    type: "Tropical foliage plant",
    difficulty: "Challenging",
    light: "Low to bright indirect (no direct sun)",
    watering: "Moderate",
    bonus: "Air-purifying",
    petFriendly: true,
  },
  {
    name: "Alocasia polly",
    price: 24,
    image: "../images/alocasia.jpeg",
    rating: 4.0,
    id: 13,
    description:
      "Dramatic arrow-shaped leaves with bold white veins and glossy, dark green surfaces. Compact variety of Alocasia.",
    type: "Tropical foliage plant",
    difficulty: "Intermediate to Challenging",
    light: "Bright indirect light (avoid direct sun)",
    watering: "Keep soil consistently moist (not soggy)",
    bonus: "Statement plant with architectural leaves",
    petFriendly: false,
  },
];
